# Generated by Django 6.0.2 on 2026-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(default=2, max_length=150, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
